---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: War
- type: document
  path: content/banner/_index.md
  label: Cold Ward
  match: "**/*"
  read_only: true
- type: heading
  label: Demo
- type: directory
  path: content/banner
  label: Goes here
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - banner
- type: heading
  label: Banner
- type: document
  path: content/banner.md
  label: Banners here
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/characters
  label: Characters
  create: all
  match: "**/*"
  templates:
  - character
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
